image: git.eleknet.dk:7900/elek/simplerss:27

before_script:
 - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
 - lint
 - test

# ktLint
lint_ktLint:
  stage: lint
  tags:
    - docker
  script:
    - ./gradlew ktlint
  artifacts:
    paths:
    - app/build/reports
    expire_in: 1 week

# Android Lint
lint_android:
  stage: lint
  tags:
    - docker
  script:
    - ./gradlew lint
  artifacts:
    paths:
    - app/build/reports
    expire_in: 1 week

# Detekt
lint_detekt:
  stage: lint
  tags:
    - docker
  script:
    - ./gradlew detekt
  artifacts:
    paths:
    - app/build/reports
    expire_in: 1 week

# Test
test:
  stage: test
  tags:
    - docker
  script:
    - ./gradlew testDebugUnitTest
